---
- name: Configure host.
  hosts: all

  vars_files:
    - config.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']
    - role: geerlingguy.mac.mas
      when: mas_installed_apps or mas_installed_app_ids
      tags: ['mas']
    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ['dock']

  tasks:

    - import_tasks: tasks/osx.yml
      when: configure_osx
      tags: ['osx']

    - import_tasks: tasks/extra-packages.yml
      tags: ['extra-packages']

    - name: Run post-provision task files in a block.
      tags: ['post']
      block:
        - name: Run configured post-provision ansible task files.
          include_tasks: "{{ outer_item }}"
          loop_control:
            loop_var: outer_item
          with_fileglob: "{{ post_provision_tasks | default(omit) }}"

    - name: Install msft brew packages with license acceptance
      include_tasks: tasks/mssql-tools.yml
      tags: ['mssql-tools']

    - name: Setup symlinks
      include_tasks: tasks/symlinks.yml
      tags: ['symlinks']

    - name: Setup custom scripts
      include_tasks: tasks/custom-scripts.yml
      tags: ['scripts']

    - name: Setup dotnet
      include_tasks: tasks/dotnet.yml
      tags: ['dotnet']

    - name: Setup ruby
      include_tasks: tasks/ruby.yml
      tags: ['ruby']

    - name: Setup Java
      include_tasks: tasks/java.yml
      tags: ['java']

    - name: Setup nodejs
      include_tasks: tasks/nodejs.yml
      tags: ['nodejs']
