---
- name: Ensure goenv is installed
  homebrew:
    name: goenv
    state: present
  tags: ['go']

- name: Add Go versions to goenv
  command:
    cmd: '{{ lookup("env", "HOMEBREW_PREFIX") }}/bin/goenv install {{ item }}'
    creates: '{{ ansible_env.HOME }}/.goenv/versions/{{ item }}'
  loop:
    - 1.23
    - 1.22
  tags: ['go']
